name: R environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-stringr
  - r-kernlab
  - r-randomforest
  - r-ellipse
  - r-caret
  - r-e1071
  - r-xgboost
  - r-nnet
  - r-keras
